apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
data:
  INDEX_NAME: "hybrid-search-langchain-pinecone-pdf"
  INDEX_NAME_CACHE: "rag-cache-index"
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_NAME: "hr_portal"
  OLLAMA_BASE_URL: "http://ollama-service:11434"
