apiVersion: v1
kind: Secret
metadata:
  name: rag-secret
type: Opaque
stringData:
  PINECONE_API_KEY: "YOUR_PINECONE_API_KEY_HERE"
  HF_TOKEN: "YOUR_HUGGINGFACE_TOKEN_HERE"
  DB_PASSWORD: "YOUR_DB_PASSWORD_HERE"
